Tutorial na podstawie:
- http://docs.julialang.org/en/stable/manual
- materialow Piotra Gawrona (Instytut Informatyki Teoretycznej i Stosowanej PAN)

Zawartosc:
- Zmienne
- Liczby całkowite i zmiennoprzecinkowe
- Operacje matematyczne i funkcje elementarne
- Liczby zespolone i wymierne
- Ciągi znaków
- Funkcje
- Kontrola przepływu
- Zakres zmiennych

---
## Zmienne
---
 Uwaga: Raz zdefiniowane zmienne, funkcje zostana zapamietane, jesli chcemy wyczyscic przestrzen nazw nalezy zrestartowac Kernel (Kernel->Restart)


In [1]:
# Przypisanie wartości do zmiennej
x = 42

42

In [2]:
# Operacja matematyczna
x + 1

43

In [3]:
# Nadpisanie zmiennej
x = 21 + 10

31

In [4]:
x = "Do zmiennej można przypisać wartość dowolnego typu"

"Do zmiennej można przypisać wartość dowolnego typu"

In [5]:
# Małe i duże litery mają znaczenie
X = 10
x = 11
X-x

-1

In [6]:
# Zmienne mogą być zapisane w Unikodzie
bździągwa = "To dobra zmienna"

"To dobra zmienna"

In [7]:
李 = "克强主持召开国务院常务会议"

"克强主持召开国务院常务会议"

In [8]:
# mozna uzyskac symbole uzywajac notacji latexa np. \alpha\_3(w Jupiterze nalezy zatwierdzic klawiszem tab)
α₃=1 

1

## Dozwolone zmienne
---
Nazwy zmienny muszą się zaczynać od 
+ A-Z, a-z, 
+ \_ - podkreślenia,
+ podzbioru kodów Unikodów większych od 00A0 w tym kategorie znaków
    - Lu/Ll/Lt/Lm/Lo/Nl (litery),
    - Sc/So (symbole walut i inne symbole),
    - kilka znaków podobnych do liter (symbole Sm)
    
Dalsze znaki mogą zawierać 
+ ! - wykrzyknik,
+ 0-9 oraz inne znaki z kategorii Nd/No,
+ inne kody Unikodu takie jak akcenty oraz znaki modyfikujące  Mn/Mc/Me/Sk,
+ znaki przestankowe z kategorii PC,
+ i kilka innych...

## Styl
---
+ Zmienne są nazywane małymi literami.
+ Można dzielić wyrazy używając podkreślenia „```_```”, ale nie powinno się tego robić.
+ Nazwy typów i modłów zaczynają się od dużej litery z użyciem tzw. _camel case_.
+ Nazwy funkcji i makr zaczynają się od małej litery.
+ Funkcje, które zmieniają swoje parametry kończą się na wykrzyknik „```!```”.

## Wprowadzanie zmiennych
---

## Zmienne całkowite
---
### Ograniczone

| Typ  | Znak?  | wielkość w bitach  | wartość najmniejsza  | wartość największa |
| - | - | - | - | - | 
| ```Int8```  | ✓  | 8  | -2^7  | 2^7 - 1 | 
| ```UInt8```  |    | 8  | 0  | 2^8 - 1 |
| ```Int16``` | ✓  | 16  | -2^15  | 2^15 - 1 |
| ```UInt16```  |    | 16  | 0  | 2^16 - 1 |
| ```Int32```  | ✓  | 32  | -2^31  | 2^31 - 1 |
| ```UInt32```  |    | 32  | 0  | 2^32 - 1 |
| ```Int64```  | ✓  | 64  | -2^63  | 2^63 - 1 |
| ```UInt64```  |    | 64  | 0  | 2^64 - 1 |
| ```Int128```  | ✓  | 128  | -2^127  | 2^127 - 1 |
| ```UInt128```  |    | 128  | 0  | 2^128 - 1 |
| ```Bool```  | N/A  | 8  | false (0)  | true (1) |

### Nieograniczone
```BigInt``` - liczby całkowite dowolnie duże. Wolne.

In [9]:
# Domyślny typ literału zależy od architektury komputera
typeof(42)

Int64

In [10]:
# Typy Int oraz UInt oznaczają (U)Int32 lub (U)Int64 w zależności od architektury
Int, UInt

(Int64, UInt64)

In [11]:
# literały heksadecymalne zaczyna się od 0x
0x123456789abcdef

0x0123456789abcdef

In [12]:
# literały binarne zaczyna się od 0b
0b1001010

0x4a

In [13]:
# literały oktalne zaczyna się od 0o
0o067312

0x00006eca

In [14]:
# funkcje typemin() i typemax() zwracają wartość minimalną i maksymalną typu całkowitego
typemin(UInt32),typemax(UInt32)

(0x00000000, 0xffffffff)

In [15]:
(typemin(Int64), typemax(Int64))

(-9223372036854775808, 9223372036854775807)

In [1]:
# zachowanie w przypadku przepełnienia
# dla Int32 mamy promocję do Int64
typemax(Int32)+1, typemax(Int32)

(2147483648, 2147483647)

In [2]:
typeof(typemax(Int32)+1)

Int64

In [18]:
# dla Int64 mamy
typemax(Int64)+1, typemin(Int64)

(-9223372036854775808, -9223372036854775808)

In [19]:
# BigInt może przechowywać dowolnie duże liczby całkowite
x = typemax(Int128)

170141183460469231731687303715884105727

In [20]:
BigInt(x)+1

170141183460469231731687303715884105728

## Zmienne zmiennoprzecinkowe
---

In [21]:
# zmienne zmiennoprzecinkowe (floaty) zapisuje się w sposób naturalny
1.0

1.0

In [22]:
1.

1.0

In [23]:
0.5

0.5

In [24]:
.5

0.5

In [25]:
# zapis inżynierski
1e10

1.0e10

In [26]:
 2.5e-4

0.00025

In [27]:
# typy floatów
typeof(0.1)

Float64

In [3]:
# 'f' zamiast 'e' oznacza Float32
0.1f0, typeof(0.1f0), 0.1f-3, typeof(0.1f-3)

(0.1f0, Float32, 0.0001f0, Float32)

In [29]:
# Istnieją jeszcze Float16
Float16(2.0)

Float16(2.0)

In [4]:
# znak '_' może być uzyty dla przejrzystości 
10_000, 0.000_000_005, 0xdead_beef, 0b1011_0010


(10000, 5.0e-9, 0xdeadbeef, 0xb2)

### Dokładność obliczeń zmiennoprzecinkowych

In [30]:
# funkcja eps() zwraca wartość bezwzględną różnicy pomiedzy daną liczbą a następną liczbą zmiennoprzecinkową
bits(Float16(0.0))

"0000000000000000"

In [31]:
bits(Float16(0.0)+eps(Float16(0.0)))

"0000000000000001"

In [32]:
eps(Float16)

Float16(0.000977)

In [33]:
eps(Float32)

1.1920929f-7

In [34]:
eps()

2.220446049250313e-16

In [35]:
eps(1.0)

2.220446049250313e-16

In [36]:
eps(1000.0)

1.1368683772161603e-13

In [37]:
eps(1000000.0)

1.1641532182693481e-10

# Operacje matematyczne
---
## Wyrażenia arytmetyczne
| wyrażenie | opis |
| - | -| 
|+x | identyczność |	
|-x | liczba ujemna |	
|x + y | dodawanie |	
|x - y | odejmowanie |	
|x * y | mnożenie |	
|x / y | dzielenie |
|x \ y | dzielenie równe y/x |
|x ^ y | potęga |
|x % y | reszta z dzielenia całkowitego |

## Negacja boolowska
| wyrażenie | opis |
| - | -| 
| !x | negacja zmiennej boolowskiej x |

## Operacje bitowe
---
| wyrażenie | opis |
| - | -| 
| `~x` | 	negacja bitowa |
| `x & y` |  koniunkcja bitowa (and)	|
| <code>x &#124; y</code> | alternatywa bitowa (or) |
| `x $ y` |  alternatywa wykluczająca (xor)	|
| `x >>> y` | logiczne przesunięcie w prawo |
| `x >> y` | 	arytmetyczne przesunięcie w prawo |
| `x << y` | 	arytmetyczne/logiczne przesunięcie w lewo |

Operacje arytmetyczne, logiczne i bitowe mogą być w wersji aktualizującej zmienną

`+=  -=  *=  /=  \=  ÷=  %=  ^=  &=`  <code> &#124;=</code>  `$=  >>>=  >>=  <<=`

In [38]:
x=1
x*=4 # x=x*4

4

In [39]:
x/=3 # x=x/3

1.3333333333333333

## Operacje porównania
---
| wyrażenie | opis |
| - | -| 
| `==` | równość| 
| `!= ≠` | nierówność | 
| `<` | mniejszy | 
| `<= ≤` | 	mniejszy lub równy | 
| `>`  | większy | 
| `>= ≥` | większy lub równy | 

In [40]:
# Porównania można łączyć jak w Pythonie
1 < 2 <= 2 < 3 == 3 > 2 >= 1 == 1 < 3 != 5

true

Operacje z kropką: np.: `.*` działają na elementy tablic.

In [41]:
A = [[1 2];[3 4]]
B = [[5 6];[7 8]]

2×2 Array{Int64,2}:
 5  6
 7  8

In [42]:
A.*B

2×2 Array{Int64,2}:
  5  12
 21  32

In [146]:
A*B

2×2 Array{Int64,2}:
 19  22
 43  50

In [44]:
 #tablice indeksowane sa od 1
C=[10,20,30]

3-element Array{Int64,1}:
 10
 20
 30

In [45]:
C[1]

10

# Liczby zespolone i wymierne
---

## Liczby zespolone
---

In [46]:
x = 1 + 2im

1 + 2im

In [47]:
typeof(x)

Complex{Int64}

In [48]:
x = 1.0 + 2.0im

1.0 + 2.0im

In [49]:
typeof(x)

Complex{Float64}

In [50]:
(1 + 2im)*(2 - 3im)

8 + 1im

In [51]:
(1 + 2im)/(1 - 2im)

-0.6 + 0.8im

In [52]:
(1 + 2im) + (1 - 2im)

2 + 0im

In [53]:
(-3 + 2im) - (5 - 1im)

-8 + 3im

In [54]:
(-1 + 2im)^2

-3 - 4im

In [55]:
(-1 + 2im)^2.5

2.7296244647840084 - 6.960664459571898im

In [56]:
(-1 + 2im)^(1 + 1im)

-0.27910381075826657 + 0.08708053414102428im

In [57]:
real(1 + 2im)

1

In [58]:
imag(1 + 2im)

2

In [59]:
conj(1 + 2im)

1 - 2im

In [60]:
abs(1 + 2im)

2.23606797749979

In [61]:
abs2(1 + 2im)

5

In [62]:
angle(1 + 2im)

1.1071487177940904

## Liczby wymierne
---

In [63]:
2//3

2//3

In [64]:
6//9

2//3

In [65]:
-4//8

-1//2

In [66]:
num(2//3)

2

In [67]:
den(2//3)

3

In [68]:
2//3 == 6//9

true

In [69]:
2//3 == 9//27

false

In [70]:
3//7 < 1//2

true

In [71]:
2//4 + 1//6

2//3

In [72]:
5//8 * 3//12

5//32

In [73]:
6//5 / 10//7

21//25

## Znaki i ciągi
---

### Znaki

In [74]:
'x'

'x': ASCII/Unicode U+0078 (category Ll: Letter, lowercase)

In [75]:
typeof(ans)

Char

In [76]:
Int('x')

120

In [77]:
typeof(ans)

Int64

In [78]:
Char(120)

'x': ASCII/Unicode U+0078 (category Ll: Letter, lowercase)

### Unicode

In [79]:
'\u0'

'\0': ASCII/Unicode U+0000 (category Cc: Other, control)

In [80]:
'\u78'

'x': ASCII/Unicode U+0078 (category Ll: Letter, lowercase)

In [81]:
'\u2200'

'∀': Unicode U+2200 (category Sm: Symbol, math)

In [82]:
Char(0x110000)

'\U110000': Unicode U+110000 (category Cn: Other, not assigned)

In [83]:
isvalid(Char, 0x110000)

false

### Ciągi znaków

In [84]:
str = "Hello, world.\n"

"Hello, world.\n"

In [85]:
"""Contains "quote" characters"""

"Contains \"quote\" characters"

In [86]:
str[1], str[5], str[end], str[end-1],  str[end÷2]

('H', 'o', '\n', '.', ' ')

In [87]:
str[4:9]

"lo, wo"

UTF-8

Łączenie ciągów znaków

In [88]:
greet = "Hello"
whom = "world"
string(greet, ", ", whom, ".\n")

"Hello, world.\n"

In [89]:
"$greet, $whom.\n"

"Hello, world.\n"

In [90]:
"1 + 2 = $(1 + 2)"

"1 + 2 = 3"

Użyteczne funkcje

In [91]:
search("bździągwa", 'ą')

7

In [92]:
contains("bździągwa.", "ziąg")

true

## Funkcje

In [93]:
# Funkcja zwraca ostatnie wyrażenie
function f(x,y)
  x + y
end
f(1,2)

3

In [94]:
# Skrócony zapis prostych funkcji
f1(x,y) = x + y
f1(1,2)

3

In [95]:
# Funkcje są zmiennymi
g = f
g(1,2)

3

In [96]:
# Wykonanie funkcji może zostać przerwane poprzez użycie słowa return
function h(x,y)
  return x * y
  x + y
end
h(1,2)

2

In [97]:
# działania to zwykłe funkcje
(+)(2,3,4)

9

In [98]:
# można tworzyć własne działania
f2(x,y) = x + 2y
const ∘= f2
2∘5∘6 

24

In [99]:
# Funkcje anonimowe (lambda)
x -> x^2 + 2x - 1

(::#1) (generic function with 1 method)

In [100]:
function (x)
    x^2 + 2x - 1
end

(::#3) (generic function with 1 method)

In [101]:
# nakładanie funkcji na tablicę
map(x -> x^2 + 2x - 1, [1,3,-1])

3-element Array{Int64,1}:
  2
 14
 -2

In [102]:
# Funkcja może zwracać wiele wartości
function foo(a,b)
    a + b, a * b
end
foo(2,3)

(5, 6)

In [103]:
# możemy użyć słowa return
function foo2(a,b)
  return a + b, a * b
end
foo2(2,3)

(5, 6)

In [104]:
# funkcje mogą brać argumenty nienazwane 
bar(a, b, x...) = (a, b, x)

bar (generic function with 1 method)

In [105]:
bar(1, 2)

(1, 2, ())

In [106]:
bar(1, 2, 3)

(1, 2, (3,))

In [107]:
bar(1, 2, 3, 4)

(1, 2, (3, 4))

In [108]:
bar(1, 2, 3, 4, 5, 6)

(1, 2, (3, 4, 5, 6))

In [109]:
# możemy przekazywać krotke do funkcji z wykorzystaniem operatora splat
x = (3, 4)
bar(1,2,x...)

(1, 2, (3, 4))

In [110]:
# możemy rozwijać krotkę w argumenty funkcji
((a, b)-> a + b)(x...)

7

In [111]:
# a to nie zadziała
x = (3, 4, 5, 6)
((a, b) -> a + b)(x...)

LoadError: MethodError: no method matching (::##9#10)(::Int64, ::Int64, ::Int64, ::Int64)
Closest candidates are:
  #9(::Any, ::Any) at In[111]:3

In [112]:
# argumenty opcjonalne
function bar(a, b, c=10)
    a + b * c
end
bar(2,3)

32

In [113]:
bar(2, 3, 4)

14

In [114]:
# keyword arguments
function toto(x, y; w1=10, w2=20)
    (x + y) * w1 + w2
end
toto(2, 3; w2=5)

55

In [115]:
function f(x, args...; y=0, kwargs...)
    return x,args,y,kwargs
end
f(1, 2, 3, 4; y=5, z=6, ź=7)

(1, (2, 3, 4), 5, Any[(:z, 6), (:ź, 7)])

In [116]:
# składnia do
map(x->iseven(x),[1,2,3,4,5,6])

6-element Array{Bool,1}:
 false
  true
 false
  true
 false
  true

In [117]:
map([1,2,3,4,5,6]) do x
    iseven(x)
end

6-element Array{Bool,1}:
 false
  true
 false
  true
 false
  true

In [1]:
# idiomatyczne użycie
open("outfile", "w") do io
    write(io, "data")
end

4

Użycie jak powyżej jest możliwe dzieki takiej definicji funkcji 

```julia 
  function open(f::Function, args...)
    io = open(args...)
    try
        f(io)
    finally
        close(io)
    end
  end
```

# Kontrola przepływu
---

### Wyrażenia złożone

In [120]:
z = begin
    x = 1
    y = 2
    x + y
end

3

In [121]:
z = (x = 1; y = 2; x + y)

3

In [122]:
begin x = 1; y = 2; x + y end

3

In [123]:
(x = 1;
y = 2;
x + y)

3

### Wykonanie warunkowe

In [124]:
# if, elseif else
function test1(x, y)
    if x < y
        return "x is less than y"
    elseif x > y
        return "x is greater than y"
    else
        return "x is equal to y"
    end
end
test1(1,2)

"x is less than y"

In [125]:
test1(2,1)

"x is greater than y"

In [126]:
test1(2,2)

"x is equal to y"

In [127]:
# z bloku if zmienne pojawiają się w bloku wyżej
function test2(x,y)
     if x < y
       relation = "less than"
     elseif x == y
       relation = "equal to"
     else
       relation = "greater than"
     end
    return "x is $relation, y."
end
test2(1,2)

"x is less than, y."

In [128]:
function test3(x,y)
         if x < y
           relation = "less than"
         elseif x == y
           relation = "equal to"
         end
         return "x is $relation, y."
       end
test3(1,2)

"x is less than, y."

In [129]:
test3(2,1)

LoadError: UndefVarError: relation not defined

In [130]:
# blok if zwraca zmienne
x = 3
if x > 0
   "positive!"
else
   "negative..."
end
"positive!"

"positive!"

In [131]:
# if bierze tylko zmienne boolowskie!
if 1
    (1,2,3)
end

LoadError: TypeError: non-boolean (Int64) used in boolean context

###  Operator trójargumentowy

In [132]:
# operator trójargumentowy
x = 1; y = 0;
x < y ? "less than" : "not less than"

"not less than"

In [133]:
# Pętla while
i = 1
while i <= 5
    i += 1
end
i

6

### Pętle

In [134]:
# pętla for
i = 1
for j = 1:5
    i += j
end
i

16

In [135]:
i = 0
for j in [1,4,10]
    i += j
end
i

15

In [136]:
# break, continue
i=1
while true
    if i >= 5
        break
    end
    i += 1
end
i

5

In [137]:
# pętla po wielu zmiennych
for i = 1:2, j = 3:4
    println((i,j))
end

(1, 3)
(1, 4)
(2, 3)
(2, 4)


### Składnia "dot"
Uzywamy, żeby zastosować daną funkcję f(x) do każdego elementu tablicy/kolekcji A, aby uzyskać nową tablicę/kolekcję za pomocą f(A).

f.(Args ...) pozwala na działanie na wielu tablicach (nawet o różnych kształtach) lub na kombinacji tablic i skalarów
poprzez mechanizm funkcji broadcast https://docs.julialang.org/en/stable/stdlib/arrays/#Base.broadcast

In [3]:
f(x,y) = 3x + 4y;
A = [1.0, 2.0, 3.0];
B = [4.0, 5.0, 6.0];
f(pi, A)

3-element Array{Float64,1}:
 13.4248
 17.4248
 21.4248

In [4]:
# to samo co:
[3*pi+4*A[1],3*pi+4*A[2],3*pi+4*A[3] ]

3-element Array{Float64,1}:
 13.4248
 17.4248
 21.4248

In [9]:
f1(x,y)=x*y
f1.(A,B)

3-element Array{Float64,1}:
  4.0
 10.0
 18.0

In [12]:
f1(A,B)

LoadError: DimensionMismatch("Cannot multiply two vectors")

In [13]:
# Macro .@ wprowadza '.' do każdej funkcji:
@. f1(A,B)

3-element Array{Float64,1}:
  4.0
 10.0
 18.0

W przypadku wielu funkcji "dot" zostaje dokonana tzw fuzja . Np. wywołanie sin.(cos.(X)) generuje tylko jedną pętlę nad X (podobną do [sin(cos(x)) for x in X]), a dla wyniku przydzielana jest pojedyncza tablica.

# Zakres zmiennych
---
Zakres zmiennych, to fragment kodu, gdzie dana nazwa zmiennej wskazuje na dane miejsce w pamięci.

W Julii następujące bloki tworzą nowe zakresy:
- ciała funkcji,
- pętle `while`,
- pętle `for`,
- blok `let`,
- bloki `try`,
- bloki `catch`,
- bloki `finally`,
- bloki typów.

Uwaga bloki:
- `if`,
- `begin`
NIE tworzą nowych zakresów zmiennych.


In [138]:
# Funkcja dziedziczy  zmienne po zakresie jej definicji
function foo()
  x
end

function bar()
  x = 1
  foo()
end

x = 2

bar()

2

In [139]:
# foo2() zdefiniowane w bar2() dziedziczy po otoczeniu bar2()
function bar2()
  function foo2()
    x
  end
  x = 1
  foo2()
end

x = 2

bar2()

1

Konstrukcje, które wprowadzają nowe zmienne do aktualnego zakresu są następujące:
- deklaracja `local x` lub `const x` wprowadza nową zmienną lokalną;
- deklaracja `global x` powoduje, że `x` w aktualnym i zagnieżdżonych zakresach odwołuje się do zmiennej globalnej `x`;
- argumenty funkcji wprowadzają nowe lokalne zmienne do zakresu ciała funkcji;
- przypisanie `x = y` wprowadza nową zmienną `x` tylko gdy `x` nie jest zadeklarowana jako globalna ani gdy nie jest ona 
wprowadzona jako lokalna zmienna w zakresie ją otaczającym - przed lub po aktualnej linii.


In [140]:
# zmienna x jest zadeklarowana na zewnątrz for
function foo5(n)
  x = 0
  for i = 1:n
    x = x + 1
  end
  x
end

foo5(10)

10

In [141]:
# zmienna x jest jawnie lokalna
function foo6(n)
  x = 0
  for i = 1:n
    local x
    x = i
  end
  x
end

foo6(10)

0

In [142]:
# zzz42 lokalne dla for nie wypływa do zakresu ciała funkcji, foo chce zwrócić globalne zzz42, które nie istnieje
function foo7(n)
  for i = 1:n
    zzz42 = i
  end
  zzz42
end

foo7(10)

LoadError: UndefVarError: zzz42 not defined

In [143]:
Fs = Array{Any}(2)
i = 1
while i <= 2
  Fs[i] = ()->i
  i += 1
end
Fs[1](),Fs[2]()

(3, 3)

In [144]:
# instrukcja let  alokuje nową  zmienną przy każdym uruchomieniu.
Fs = Array{Any}(2)
i = 1
while i <= 2
  let i = i
    Fs[i] = ()->i
  end
  i += 1
end

Fs[1](), Fs[2]()

(1, 2)

In [145]:
function ala()
    a = 1
    object_id(a)|> println
    begin
        object_id(a)|> println
        let a = 2
            object_id(a)|> println
        end
    end
    object_id(a)|> println
end
ala();

11967854120867199718
11967854120867199718
5352850025288631388
11967854120867199718
